name: ZMK Firmware Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install West + deps
        run: |
          sudo apt update
          sudo apt install -y python3-pip cmake ninja-build g++ wget
          pip3 install west

      - name: Clone ZMK app
        run: |
          git clone https://github.com/zmkfirmware/zmk.git app

      - name: Init West + Zephyr
        run: |
          west init -l app
          west update

      - name: Build firmware (nice!nano)
        run: |
          west build -s app -b nice_nano -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/zmk.uf2
