name: ZMK Firmware Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y python3-pip cmake ninja-build g++ wget
          pip3 install west

      - name: Clone ZMK into app/
        run: |
          rm -rf app
          git clone https://github.com/zmkfirmware/zmk.git app
          ls -la app

      - name: Init West and update modules
        run: |
          west init -l app
          west update

      - name: Build firmware (nice_nano_v2)
        run: |
          west build -s app -b nice_nano_v2 -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: zmk-34_nice_nano_v2
          path: build/zephyr/zmk.uf2
